# Site settings
title: Noix.io
email: clement.drevo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Noix.io
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: CDrevo
github_username:  CDrevo

# Build settings
markdown: kramdown
